set_property SRC_FILE_INFO {cfile:/home/lf-securitas/Documentos/ISPR/lab2/lab2.srcs/constrs_1/imports/src/lab1_zybo.xdc rfile:../../../lab2.srcs/constrs_1/imports/src/lab1_zybo.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lf-securitas/Documentos/ISPR/lab2/lab2.srcs/constrs_1/imports/lab2/lab2_zybo.xdc rfile:../../../lab2.srcs/constrs_1/imports/lab2/lab2_zybo.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports btn_tri_io]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {leds[3]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {leds[2]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {leds[1]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {leds[0]}]
