// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct_1d2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_1d2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_1d2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> dct_1d2::ap_ST_fsm_state1 = "1";
const sc_lv<4> dct_1d2::ap_ST_fsm_state2 = "10";
const sc_lv<4> dct_1d2::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> dct_1d2::ap_ST_fsm_state6 = "1000";
const bool dct_1d2::ap_const_boolean_1 = true;
const sc_lv<32> dct_1d2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dct_1d2::ap_const_lv32_1 = "1";
const sc_lv<1> dct_1d2::ap_const_lv1_0 = "0";
const sc_lv<32> dct_1d2::ap_const_lv32_2 = "10";
const bool dct_1d2::ap_const_boolean_0 = false;
const sc_lv<1> dct_1d2::ap_const_lv1_1 = "1";
const sc_lv<4> dct_1d2::ap_const_lv4_0 = "0000";
const sc_lv<32> dct_1d2::ap_const_lv32_3 = "11";
const sc_lv<3> dct_1d2::ap_const_lv3_0 = "000";
const sc_lv<4> dct_1d2::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_1d2::ap_const_lv4_1 = "1";
const sc_lv<29> dct_1d2::ap_const_lv29_1000 = "1000000000000";
const sc_lv<32> dct_1d2::ap_const_lv32_D = "1101";
const sc_lv<32> dct_1d2::ap_const_lv32_1C = "11100";

dct_1d2::dct_1d2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_U = new dct_1d2_dct_coeffbkb("dct_coeff_table_U");
    dct_coeff_table_U->clk(ap_clk);
    dct_coeff_table_U->reset(ap_rst);
    dct_coeff_table_U->address0(dct_coeff_table_address0);
    dct_coeff_table_U->ce0(dct_coeff_table_ce0);
    dct_coeff_table_U->q0(dct_coeff_table_q0);
    dct_mac_muladd_15cud_U1 = new dct_mac_muladd_15cud<1,1,15,16,32,32>("dct_mac_muladd_15cud_U1");
    dct_mac_muladd_15cud_U1->din0(dct_coeff_table_load_reg_318);
    dct_mac_muladd_15cud_U1->din1(src_load_reg_323);
    dct_mac_muladd_15cud_U1->din2(tmp1_reg_125);
    dct_mac_muladd_15cud_U1->dout(grp_fu_262_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_11_fu_199_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_161_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_fu_161_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_dct_coeff_table_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( tmp_28_cast_fu_230_p1 );

    SC_METHOD(thread_dct_coeff_table_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dst_address0);
    sensitive << ( dst_addr_reg_289 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_dst_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_dst_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_12_fu_245_p2 );

    SC_METHOD(thread_dst_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_k_1_fu_167_p2);
    sensitive << ( k_reg_103 );

    SC_METHOD(thread_n_1_fu_205_p2);
    sensitive << ( n_reg_114 );

    SC_METHOD(thread_src_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_27_cast_fu_220_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_11_fu_199_p2);
    sensitive << ( n_reg_114 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_12_fu_245_p2);
    sensitive << ( tmp_2_fu_241_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_211_p1);
    sensitive << ( n_reg_114 );

    SC_METHOD(thread_tmp_15_fu_149_p3);
    sensitive << ( tmp_6 );

    SC_METHOD(thread_tmp_16_fu_177_p2);
    sensitive << ( tmp_21_cast_reg_270 );
    sensitive << ( tmp_cast_fu_173_p1 );

    SC_METHOD(thread_tmp_19_fu_187_p3);
    sensitive << ( k_reg_103 );

    SC_METHOD(thread_tmp_20_fu_215_p2);
    sensitive << ( tmp_23_cast_reg_275 );
    sensitive << ( tmp_15_cast_fu_211_p1 );

    SC_METHOD(thread_tmp_21_cast_fu_145_p1);
    sensitive << ( tmp_s_fu_137_p3 );

    SC_METHOD(thread_tmp_21_fu_225_p2);
    sensitive << ( tmp_26_cast_reg_294 );
    sensitive << ( tmp_15_cast_fu_211_p1 );

    SC_METHOD(thread_tmp_23_cast_fu_157_p1);
    sensitive << ( tmp_15_fu_149_p3 );

    SC_METHOD(thread_tmp_24_cast_fu_182_p1);
    sensitive << ( tmp_16_fu_177_p2 );

    SC_METHOD(thread_tmp_26_cast_fu_195_p1);
    sensitive << ( tmp_19_fu_187_p3 );

    SC_METHOD(thread_tmp_27_cast_fu_220_p1);
    sensitive << ( tmp_20_fu_215_p2 );

    SC_METHOD(thread_tmp_28_cast_fu_230_p1);
    sensitive << ( tmp_21_fu_225_p2 );

    SC_METHOD(thread_tmp_2_fu_241_p1);
    sensitive << ( tmp1_reg_125 );

    SC_METHOD(thread_tmp_cast_fu_173_p1);
    sensitive << ( k_reg_103 );

    SC_METHOD(thread_tmp_fu_161_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( k_reg_103 );

    SC_METHOD(thread_tmp_s_fu_137_p3);
    sensitive << ( tmp_61 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_161_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_11_fu_199_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_1d2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_address0, "(port)src_address0");
    sc_trace(mVcdFile, src_ce0, "(port)src_ce0");
    sc_trace(mVcdFile, src_q0, "(port)src_q0");
    sc_trace(mVcdFile, tmp_6, "(port)tmp_6");
    sc_trace(mVcdFile, dst_address0, "(port)dst_address0");
    sc_trace(mVcdFile, dst_ce0, "(port)dst_ce0");
    sc_trace(mVcdFile, dst_we0, "(port)dst_we0");
    sc_trace(mVcdFile, dst_d0, "(port)dst_d0");
    sc_trace(mVcdFile, tmp_61, "(port)tmp_61");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dct_coeff_table_address0, "dct_coeff_table_address0");
    sc_trace(mVcdFile, dct_coeff_table_ce0, "dct_coeff_table_ce0");
    sc_trace(mVcdFile, dct_coeff_table_q0, "dct_coeff_table_q0");
    sc_trace(mVcdFile, n_reg_114, "n_reg_114");
    sc_trace(mVcdFile, tmp1_reg_125, "tmp1_reg_125");
    sc_trace(mVcdFile, tmp_21_cast_fu_145_p1, "tmp_21_cast_fu_145_p1");
    sc_trace(mVcdFile, tmp_21_cast_reg_270, "tmp_21_cast_reg_270");
    sc_trace(mVcdFile, tmp_23_cast_fu_157_p1, "tmp_23_cast_fu_157_p1");
    sc_trace(mVcdFile, tmp_23_cast_reg_275, "tmp_23_cast_reg_275");
    sc_trace(mVcdFile, tmp_fu_161_p2, "tmp_fu_161_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, k_1_fu_167_p2, "k_1_fu_167_p2");
    sc_trace(mVcdFile, k_1_reg_284, "k_1_reg_284");
    sc_trace(mVcdFile, dst_addr_reg_289, "dst_addr_reg_289");
    sc_trace(mVcdFile, tmp_26_cast_fu_195_p1, "tmp_26_cast_fu_195_p1");
    sc_trace(mVcdFile, tmp_26_cast_reg_294, "tmp_26_cast_reg_294");
    sc_trace(mVcdFile, tmp_11_fu_199_p2, "tmp_11_fu_199_p2");
    sc_trace(mVcdFile, tmp_11_reg_299, "tmp_11_reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_11_reg_299, "ap_reg_pp0_iter1_tmp_11_reg_299");
    sc_trace(mVcdFile, n_1_fu_205_p2, "n_1_fu_205_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, dct_coeff_table_load_reg_318, "dct_coeff_table_load_reg_318");
    sc_trace(mVcdFile, src_load_reg_323, "src_load_reg_323");
    sc_trace(mVcdFile, grp_fu_262_p3, "grp_fu_262_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, k_reg_103, "k_reg_103");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_24_cast_fu_182_p1, "tmp_24_cast_fu_182_p1");
    sc_trace(mVcdFile, tmp_27_cast_fu_220_p1, "tmp_27_cast_fu_220_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, tmp_28_cast_fu_230_p1, "tmp_28_cast_fu_230_p1");
    sc_trace(mVcdFile, tmp_s_fu_137_p3, "tmp_s_fu_137_p3");
    sc_trace(mVcdFile, tmp_15_fu_149_p3, "tmp_15_fu_149_p3");
    sc_trace(mVcdFile, tmp_cast_fu_173_p1, "tmp_cast_fu_173_p1");
    sc_trace(mVcdFile, tmp_16_fu_177_p2, "tmp_16_fu_177_p2");
    sc_trace(mVcdFile, tmp_19_fu_187_p3, "tmp_19_fu_187_p3");
    sc_trace(mVcdFile, tmp_15_cast_fu_211_p1, "tmp_15_cast_fu_211_p1");
    sc_trace(mVcdFile, tmp_20_fu_215_p2, "tmp_20_fu_215_p2");
    sc_trace(mVcdFile, tmp_21_fu_225_p2, "tmp_21_fu_225_p2");
    sc_trace(mVcdFile, tmp_2_fu_241_p1, "tmp_2_fu_241_p1");
    sc_trace(mVcdFile, tmp_12_fu_245_p2, "tmp_12_fu_245_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

dct_1d2::~dct_1d2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_U;
    delete dct_mac_muladd_15cud_U1;
}

void dct_1d2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        k_reg_103 = k_1_reg_284.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_reg_103 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_199_p2.read()))) {
        n_reg_114 = n_1_fu_205_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_0))) {
        n_reg_114 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_11_reg_299.read()))) {
        tmp1_reg_125 = grp_fu_262_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_0))) {
        tmp1_reg_125 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_tmp_11_reg_299 = tmp_11_reg_299.read();
        tmp_11_reg_299 = tmp_11_fu_199_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_299.read()))) {
        dct_coeff_table_load_reg_318 = dct_coeff_table_q0.read();
        src_load_reg_323 = src_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_0))) {
        dst_addr_reg_289 =  (sc_lv<6>) (tmp_24_cast_fu_182_p1.read());
        tmp_26_cast_reg_294 = tmp_26_cast_fu_195_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        k_1_reg_284 = k_1_fu_167_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_21_cast_reg_270 = tmp_21_cast_fu_145_p1.read();
        tmp_23_cast_reg_275 = tmp_23_cast_fu_157_p1.read();
    }
}

void dct_1d2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void dct_1d2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dct_1d2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dct_1d2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d2::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(tmp_11_fu_199_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dct_1d2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_1d2::thread_dct_coeff_table_address0() {
    dct_coeff_table_address0 =  (sc_lv<6>) (tmp_28_cast_fu_230_p1.read());
}

void dct_1d2::thread_dct_coeff_table_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        dct_coeff_table_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dst_address0() {
    dst_address0 = dst_addr_reg_289.read();
}

void dct_1d2::thread_dst_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        dst_ce0 = ap_const_logic_1;
    } else {
        dst_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_dst_d0() {
    dst_d0 = tmp_12_fu_245_p2.read().range(28, 13);
}

void dct_1d2::thread_dst_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        dst_we0 = ap_const_logic_1;
    } else {
        dst_we0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_k_1_fu_167_p2() {
    k_1_fu_167_p2 = (!k_reg_103.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_reg_103.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_1d2::thread_n_1_fu_205_p2() {
    n_1_fu_205_p2 = (!n_reg_114.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(n_reg_114.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_1d2::thread_src_address0() {
    src_address0 =  (sc_lv<6>) (tmp_27_cast_fu_220_p1.read());
}

void dct_1d2::thread_src_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        src_ce0 = ap_const_logic_1;
    } else {
        src_ce0 = ap_const_logic_0;
    }
}

void dct_1d2::thread_tmp_11_fu_199_p2() {
    tmp_11_fu_199_p2 = (!n_reg_114.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(n_reg_114.read() == ap_const_lv4_8);
}

void dct_1d2::thread_tmp_12_fu_245_p2() {
    tmp_12_fu_245_p2 = (!ap_const_lv29_1000.is_01() || !tmp_2_fu_241_p1.read().is_01())? sc_lv<29>(): (sc_biguint<29>(ap_const_lv29_1000) + sc_biguint<29>(tmp_2_fu_241_p1.read()));
}

void dct_1d2::thread_tmp_15_cast_fu_211_p1() {
    tmp_15_cast_fu_211_p1 = esl_zext<8,4>(n_reg_114.read());
}

void dct_1d2::thread_tmp_15_fu_149_p3() {
    tmp_15_fu_149_p3 = esl_concat<4,3>(tmp_6.read(), ap_const_lv3_0);
}

void dct_1d2::thread_tmp_16_fu_177_p2() {
    tmp_16_fu_177_p2 = (!tmp_cast_fu_173_p1.read().is_01() || !tmp_21_cast_reg_270.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_cast_fu_173_p1.read()) + sc_biguint<8>(tmp_21_cast_reg_270.read()));
}

void dct_1d2::thread_tmp_19_fu_187_p3() {
    tmp_19_fu_187_p3 = esl_concat<4,3>(k_reg_103.read(), ap_const_lv3_0);
}

void dct_1d2::thread_tmp_20_fu_215_p2() {
    tmp_20_fu_215_p2 = (!tmp_23_cast_reg_275.read().is_01() || !tmp_15_cast_fu_211_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_23_cast_reg_275.read()) + sc_biguint<8>(tmp_15_cast_fu_211_p1.read()));
}

void dct_1d2::thread_tmp_21_cast_fu_145_p1() {
    tmp_21_cast_fu_145_p1 = esl_zext<8,7>(tmp_s_fu_137_p3.read());
}

void dct_1d2::thread_tmp_21_fu_225_p2() {
    tmp_21_fu_225_p2 = (!tmp_26_cast_reg_294.read().is_01() || !tmp_15_cast_fu_211_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_26_cast_reg_294.read()) + sc_biguint<8>(tmp_15_cast_fu_211_p1.read()));
}

void dct_1d2::thread_tmp_23_cast_fu_157_p1() {
    tmp_23_cast_fu_157_p1 = esl_zext<8,7>(tmp_15_fu_149_p3.read());
}

void dct_1d2::thread_tmp_24_cast_fu_182_p1() {
    tmp_24_cast_fu_182_p1 = esl_zext<64,8>(tmp_16_fu_177_p2.read());
}

void dct_1d2::thread_tmp_26_cast_fu_195_p1() {
    tmp_26_cast_fu_195_p1 = esl_zext<8,7>(tmp_19_fu_187_p3.read());
}

void dct_1d2::thread_tmp_27_cast_fu_220_p1() {
    tmp_27_cast_fu_220_p1 = esl_zext<64,8>(tmp_20_fu_215_p2.read());
}

void dct_1d2::thread_tmp_28_cast_fu_230_p1() {
    tmp_28_cast_fu_230_p1 = esl_zext<64,8>(tmp_21_fu_225_p2.read());
}

void dct_1d2::thread_tmp_2_fu_241_p1() {
    tmp_2_fu_241_p1 = tmp1_reg_125.read().range(29-1, 0);
}

void dct_1d2::thread_tmp_cast_fu_173_p1() {
    tmp_cast_fu_173_p1 = esl_zext<8,4>(k_reg_103.read());
}

void dct_1d2::thread_tmp_fu_161_p2() {
    tmp_fu_161_p2 = (!k_reg_103.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_103.read() == ap_const_lv4_8);
}

void dct_1d2::thread_tmp_s_fu_137_p3() {
    tmp_s_fu_137_p3 = esl_concat<4,3>(tmp_61.read(), ap_const_lv3_0);
}

void dct_1d2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_161_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_11_fu_199_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_11_fu_199_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

