// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_Xpose_Row_Outer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_Xpose_Row_Outer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_Xpose_Row_Outer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Loop_Xpose_Row_Outer::ap_ST_fsm_state1 = "1";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_ST_fsm_state8 = "1000";
const sc_lv<32> Loop_Xpose_Row_Outer::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_Xpose_Row_Outer::ap_const_boolean_1 = true;
const sc_lv<32> Loop_Xpose_Row_Outer::ap_const_lv32_1 = "1";
const bool Loop_Xpose_Row_Outer::ap_const_boolean_0 = false;
const sc_lv<32> Loop_Xpose_Row_Outer::ap_const_lv32_2 = "10";
const sc_lv<1> Loop_Xpose_Row_Outer::ap_const_lv1_0 = "0";
const sc_lv<1> Loop_Xpose_Row_Outer::ap_const_lv1_1 = "1";
const sc_lv<7> Loop_Xpose_Row_Outer::ap_const_lv7_0 = "0000000";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_const_lv4_0 = "0000";
const sc_lv<7> Loop_Xpose_Row_Outer::ap_const_lv7_40 = "1000000";
const sc_lv<7> Loop_Xpose_Row_Outer::ap_const_lv7_1 = "1";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_const_lv4_1 = "1";
const sc_lv<4> Loop_Xpose_Row_Outer::ap_const_lv4_8 = "1000";
const sc_lv<3> Loop_Xpose_Row_Outer::ap_const_lv3_0 = "000";
const sc_lv<7> Loop_Xpose_Row_Outer::ap_const_lv7_F = "1111";
const sc_lv<8> Loop_Xpose_Row_Outer::ap_const_lv8_7F = "1111111";
const sc_lv<128> Loop_Xpose_Row_Outer::ap_const_lv128_lc_1 = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> Loop_Xpose_Row_Outer::ap_const_lv32_7F = "1111111";
const sc_lv<32> Loop_Xpose_Row_Outer::ap_const_lv32_3 = "11";

Loop_Xpose_Row_Outer::Loop_Xpose_Row_Outer(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage1_flag00011011);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter2);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten_fu_116_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_col_inbuf_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( col_inbuf_addr_reg_363 );
    sensitive << ( ap_reg_pp0_iter2_col_inbuf_addr_reg_363 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_col_inbuf_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_col_inbuf_d0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );
    sensitive << ( tmp_46_fu_313_p2 );
    sensitive << ( tmp_47_fu_319_p2 );

    SC_METHOD(thread_col_inbuf_we0);
    sensitive << ( ap_reg_pp0_iter2_exitcond_flatten_reg_331 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_exitcond_flatten_fu_116_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( indvar_flatten_phi_fu_85_p4 );

    SC_METHOD(thread_i_1_i_mid2_fu_140_p3);
    sensitive << ( i_1_i_phi_fu_108_p4 );
    sensitive << ( tmp_s_fu_134_p2 );

    SC_METHOD(thread_i_1_i_phi_fu_108_p4);
    sensitive << ( i_1_i_reg_104 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_flatten_reg_331 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( i_reg_368 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_i_fu_189_p2);
    sensitive << ( i_1_i_mid2_reg_340 );

    SC_METHOD(thread_indvar_flatten_next_fu_122_p2);
    sensitive << ( indvar_flatten_phi_fu_85_p4 );

    SC_METHOD(thread_indvar_flatten_phi_fu_85_p4);
    sensitive << ( indvar_flatten_reg_81 );
    sensitive << ( exitcond_flatten_reg_331 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_next_reg_335 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_j_0_i_phi_fu_96_p4);
    sensitive << ( j_0_i_reg_92 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_flatten_reg_331 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_3_mid2_v_reg_346 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1_flag00000000 );

    SC_METHOD(thread_j_fu_128_p2);
    sensitive << ( j_0_i_phi_fu_96_p4 );

    SC_METHOD(thread_p_demorgan_fu_263_p2);
    sensitive << ( tmp_43_fu_251_p2 );
    sensitive << ( tmp_44_fu_257_p2 );

    SC_METHOD(thread_row_outbuf_i_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( tmp_10_cast_fu_184_p1 );

    SC_METHOD(thread_row_outbuf_i_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp_10_cast_fu_184_p1);
    sensitive << ( tmp_1_fu_178_p2 );

    SC_METHOD(thread_tmp_1_fu_178_p2);
    sensitive << ( tmp_9_cast_fu_174_p1 );
    sensitive << ( tmp_3_mid2_cast_fu_164_p1 );

    SC_METHOD(thread_tmp_27_fu_156_p1);
    sensitive << ( i_1_i_mid2_fu_140_p3 );

    SC_METHOD(thread_tmp_28_fu_207_p2);
    sensitive << ( ap_reg_pp0_iter1_exitcond_flatten_reg_331 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_fu_194_p3 );
    sensitive << ( tmp_5_fu_201_p2 );

    SC_METHOD(thread_tmp_29_fu_213_p1);
    sensitive << ( tmp_4_fu_194_p3 );

    SC_METHOD(thread_tmp_30_fu_217_p1);
    sensitive << ( tmp_5_fu_201_p2 );

    SC_METHOD(thread_tmp_31_fu_269_p1);
    sensitive << ( row_outbuf_i_load_reg_373 );

    SC_METHOD(thread_tmp_32_fu_272_p2);
    sensitive << ( tmp_29_reg_384 );

    SC_METHOD(thread_tmp_33_fu_221_p3);
    sensitive << ( tmp_28_fu_207_p2 );
    sensitive << ( tmp_29_fu_213_p1 );
    sensitive << ( tmp_30_fu_217_p1 );

    SC_METHOD(thread_tmp_34_fu_229_p3);
    sensitive << ( tmp_28_fu_207_p2 );
    sensitive << ( tmp_29_fu_213_p1 );
    sensitive << ( tmp_30_fu_217_p1 );

    SC_METHOD(thread_tmp_35_fu_277_p3);
    sensitive << ( tmp_28_reg_378 );
    sensitive << ( tmp_29_reg_384 );
    sensitive << ( tmp_32_fu_272_p2 );

    SC_METHOD(thread_tmp_36_fu_237_p2);
    sensitive << ( tmp_33_fu_221_p3 );

    SC_METHOD(thread_tmp_37_fu_283_p1);
    sensitive << ( tmp_35_fu_277_p3 );

    SC_METHOD(thread_tmp_38_fu_243_p1);
    sensitive << ( tmp_34_fu_229_p3 );

    SC_METHOD(thread_tmp_39_fu_247_p1);
    sensitive << ( tmp_36_fu_237_p2 );

    SC_METHOD(thread_tmp_3_mid2_cast_fu_164_p1);
    sensitive << ( tmp_3_mid2_v_reg_346 );

    SC_METHOD(thread_tmp_3_mid2_fu_160_p1);
    sensitive << ( tmp_3_mid2_v_reg_346 );

    SC_METHOD(thread_tmp_3_mid2_v_fu_148_p3);
    sensitive << ( j_0_i_phi_fu_96_p4 );
    sensitive << ( tmp_s_fu_134_p2 );
    sensitive << ( j_fu_128_p2 );

    SC_METHOD(thread_tmp_40_fu_287_p2);
    sensitive << ( tmp_31_fu_269_p1 );
    sensitive << ( tmp_37_fu_283_p1 );

    SC_METHOD(thread_tmp_41_fu_293_p4);
    sensitive << ( tmp_40_reg_396 );

    SC_METHOD(thread_tmp_42_fu_302_p3);
    sensitive << ( tmp_28_reg_378 );
    sensitive << ( tmp_40_reg_396 );
    sensitive << ( tmp_41_fu_293_p4 );

    SC_METHOD(thread_tmp_43_fu_251_p2);
    sensitive << ( tmp_38_fu_243_p1 );

    SC_METHOD(thread_tmp_44_fu_257_p2);
    sensitive << ( tmp_39_fu_247_p1 );

    SC_METHOD(thread_tmp_45_fu_308_p2);
    sensitive << ( p_demorgan_reg_390 );

    SC_METHOD(thread_tmp_46_fu_313_p2);
    sensitive << ( col_inbuf_q0 );
    sensitive << ( tmp_45_fu_308_p2 );

    SC_METHOD(thread_tmp_47_fu_319_p2);
    sensitive << ( p_demorgan_reg_390 );
    sensitive << ( tmp_42_fu_302_p3 );

    SC_METHOD(thread_tmp_4_fu_194_p3);
    sensitive << ( tmp_27_reg_353 );

    SC_METHOD(thread_tmp_5_fu_201_p2);
    sensitive << ( tmp_4_fu_194_p3 );

    SC_METHOD(thread_tmp_9_cast_fu_174_p1);
    sensitive << ( tmp_fu_167_p3 );

    SC_METHOD(thread_tmp_fu_167_p3);
    sensitive << ( i_1_i_mid2_reg_340 );

    SC_METHOD(thread_tmp_s_fu_134_p2);
    sensitive << ( exitcond_flatten_reg_331 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_flag00011001 );
    sensitive << ( i_1_i_phi_fu_108_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_flatten_fu_116_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );
    sensitive << ( ap_block_pp0_stage1_flag00011011 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_Xpose_Row_Outer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, row_outbuf_i_address0, "(port)row_outbuf_i_address0");
    sc_trace(mVcdFile, row_outbuf_i_ce0, "(port)row_outbuf_i_ce0");
    sc_trace(mVcdFile, row_outbuf_i_q0, "(port)row_outbuf_i_q0");
    sc_trace(mVcdFile, col_inbuf_address0, "(port)col_inbuf_address0");
    sc_trace(mVcdFile, col_inbuf_ce0, "(port)col_inbuf_ce0");
    sc_trace(mVcdFile, col_inbuf_we0, "(port)col_inbuf_we0");
    sc_trace(mVcdFile, col_inbuf_d0, "(port)col_inbuf_d0");
    sc_trace(mVcdFile, col_inbuf_q0, "(port)col_inbuf_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_81, "indvar_flatten_reg_81");
    sc_trace(mVcdFile, j_0_i_reg_92, "j_0_i_reg_92");
    sc_trace(mVcdFile, i_1_i_reg_104, "i_1_i_reg_104");
    sc_trace(mVcdFile, exitcond_flatten_fu_116_p2, "exitcond_flatten_fu_116_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_331, "exitcond_flatten_reg_331");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_exitcond_flatten_reg_331, "ap_reg_pp0_iter1_exitcond_flatten_reg_331");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_exitcond_flatten_reg_331, "ap_reg_pp0_iter2_exitcond_flatten_reg_331");
    sc_trace(mVcdFile, indvar_flatten_next_fu_122_p2, "indvar_flatten_next_fu_122_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_335, "indvar_flatten_next_reg_335");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, i_1_i_mid2_fu_140_p3, "i_1_i_mid2_fu_140_p3");
    sc_trace(mVcdFile, i_1_i_mid2_reg_340, "i_1_i_mid2_reg_340");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter2, "ap_block_state7_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011001, "ap_block_pp0_stage1_flag00011001");
    sc_trace(mVcdFile, tmp_3_mid2_v_fu_148_p3, "tmp_3_mid2_v_fu_148_p3");
    sc_trace(mVcdFile, tmp_3_mid2_v_reg_346, "tmp_3_mid2_v_reg_346");
    sc_trace(mVcdFile, tmp_27_fu_156_p1, "tmp_27_fu_156_p1");
    sc_trace(mVcdFile, tmp_27_reg_353, "tmp_27_reg_353");
    sc_trace(mVcdFile, col_inbuf_addr_reg_363, "col_inbuf_addr_reg_363");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_col_inbuf_addr_reg_363, "ap_reg_pp0_iter2_col_inbuf_addr_reg_363");
    sc_trace(mVcdFile, i_fu_189_p2, "i_fu_189_p2");
    sc_trace(mVcdFile, i_reg_368, "i_reg_368");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, row_outbuf_i_load_reg_373, "row_outbuf_i_load_reg_373");
    sc_trace(mVcdFile, tmp_28_fu_207_p2, "tmp_28_fu_207_p2");
    sc_trace(mVcdFile, tmp_28_reg_378, "tmp_28_reg_378");
    sc_trace(mVcdFile, tmp_29_fu_213_p1, "tmp_29_fu_213_p1");
    sc_trace(mVcdFile, tmp_29_reg_384, "tmp_29_reg_384");
    sc_trace(mVcdFile, p_demorgan_fu_263_p2, "p_demorgan_fu_263_p2");
    sc_trace(mVcdFile, p_demorgan_reg_390, "p_demorgan_reg_390");
    sc_trace(mVcdFile, tmp_40_fu_287_p2, "tmp_40_fu_287_p2");
    sc_trace(mVcdFile, tmp_40_reg_396, "tmp_40_reg_396");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00011011, "ap_block_pp0_stage1_flag00011011");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, indvar_flatten_phi_fu_85_p4, "indvar_flatten_phi_fu_85_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, j_0_i_phi_fu_96_p4, "j_0_i_phi_fu_96_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1_flag00000000, "ap_block_pp0_stage1_flag00000000");
    sc_trace(mVcdFile, i_1_i_phi_fu_108_p4, "i_1_i_phi_fu_108_p4");
    sc_trace(mVcdFile, tmp_10_cast_fu_184_p1, "tmp_10_cast_fu_184_p1");
    sc_trace(mVcdFile, tmp_3_mid2_fu_160_p1, "tmp_3_mid2_fu_160_p1");
    sc_trace(mVcdFile, tmp_s_fu_134_p2, "tmp_s_fu_134_p2");
    sc_trace(mVcdFile, j_fu_128_p2, "j_fu_128_p2");
    sc_trace(mVcdFile, tmp_fu_167_p3, "tmp_fu_167_p3");
    sc_trace(mVcdFile, tmp_9_cast_fu_174_p1, "tmp_9_cast_fu_174_p1");
    sc_trace(mVcdFile, tmp_3_mid2_cast_fu_164_p1, "tmp_3_mid2_cast_fu_164_p1");
    sc_trace(mVcdFile, tmp_1_fu_178_p2, "tmp_1_fu_178_p2");
    sc_trace(mVcdFile, tmp_4_fu_194_p3, "tmp_4_fu_194_p3");
    sc_trace(mVcdFile, tmp_5_fu_201_p2, "tmp_5_fu_201_p2");
    sc_trace(mVcdFile, tmp_30_fu_217_p1, "tmp_30_fu_217_p1");
    sc_trace(mVcdFile, tmp_33_fu_221_p3, "tmp_33_fu_221_p3");
    sc_trace(mVcdFile, tmp_34_fu_229_p3, "tmp_34_fu_229_p3");
    sc_trace(mVcdFile, tmp_36_fu_237_p2, "tmp_36_fu_237_p2");
    sc_trace(mVcdFile, tmp_38_fu_243_p1, "tmp_38_fu_243_p1");
    sc_trace(mVcdFile, tmp_39_fu_247_p1, "tmp_39_fu_247_p1");
    sc_trace(mVcdFile, tmp_43_fu_251_p2, "tmp_43_fu_251_p2");
    sc_trace(mVcdFile, tmp_44_fu_257_p2, "tmp_44_fu_257_p2");
    sc_trace(mVcdFile, tmp_32_fu_272_p2, "tmp_32_fu_272_p2");
    sc_trace(mVcdFile, tmp_35_fu_277_p3, "tmp_35_fu_277_p3");
    sc_trace(mVcdFile, tmp_31_fu_269_p1, "tmp_31_fu_269_p1");
    sc_trace(mVcdFile, tmp_37_fu_283_p1, "tmp_37_fu_283_p1");
    sc_trace(mVcdFile, tmp_41_fu_293_p4, "tmp_41_fu_293_p4");
    sc_trace(mVcdFile, tmp_45_fu_308_p2, "tmp_45_fu_308_p2");
    sc_trace(mVcdFile, tmp_42_fu_302_p3, "tmp_42_fu_302_p3");
    sc_trace(mVcdFile, tmp_46_fu_313_p2, "tmp_46_fu_313_p2");
    sc_trace(mVcdFile, tmp_47_fu_319_p2, "tmp_47_fu_319_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Loop_Xpose_Row_Outer::~Loop_Xpose_Row_Outer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Loop_Xpose_Row_Outer::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0))) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        i_1_i_reg_104 = i_reg_368.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_1_i_reg_104 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_81 = indvar_flatten_next_reg_335.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten_reg_81 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        j_0_i_reg_92 = tmp_3_mid2_v_reg_346.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        j_0_i_reg_92 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_exitcond_flatten_reg_331 = exitcond_flatten_reg_331.read();
        ap_reg_pp0_iter2_col_inbuf_addr_reg_363 = col_inbuf_addr_reg_363.read();
        ap_reg_pp0_iter2_exitcond_flatten_reg_331 = ap_reg_pp0_iter1_exitcond_flatten_reg_331.read();
        exitcond_flatten_reg_331 = exitcond_flatten_fu_116_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        col_inbuf_addr_reg_363 =  (sc_lv<3>) (tmp_3_mid2_fu_160_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        i_1_i_mid2_reg_340 = i_1_i_mid2_fu_140_p3.read();
        tmp_27_reg_353 = tmp_27_fu_156_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_reg_368 = i_fu_189_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        indvar_flatten_next_reg_335 = indvar_flatten_next_fu_122_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        p_demorgan_reg_390 = p_demorgan_fu_263_p2.read();
        row_outbuf_i_load_reg_373 = row_outbuf_i_q0.read();
        tmp_28_reg_378 = tmp_28_fu_207_p2.read();
        tmp_29_reg_384 = tmp_29_fu_213_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        tmp_3_mid2_v_reg_346 = tmp_3_mid2_v_fu_148_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        tmp_40_reg_396 = tmp_40_fu_287_p2.read();
    }
}

void Loop_Xpose_Row_Outer::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Loop_Xpose_Row_Outer::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void Loop_Xpose_Row_Outer::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_Xpose_Row_Outer::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[3];
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage1_flag00000000() {
    ap_block_pp0_stage1_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage1_flag00011001() {
    ap_block_pp0_stage1_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_pp0_stage1_flag00011011() {
    ap_block_pp0_stage1_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_Xpose_Row_Outer::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_block_state7_pp0_stage1_iter2() {
    ap_block_state7_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_Xpose_Row_Outer::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_116_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_Xpose_Row_Outer::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_Xpose_Row_Outer::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_col_inbuf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00000000.read(), ap_const_boolean_0))) {
            col_inbuf_address0 = ap_reg_pp0_iter2_col_inbuf_addr_reg_363.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
            col_inbuf_address0 = col_inbuf_addr_reg_363.read();
        } else {
            col_inbuf_address0 = "XXX";
        }
    } else {
        col_inbuf_address0 = "XXX";
    }
}

void Loop_Xpose_Row_Outer::thread_col_inbuf_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        col_inbuf_ce0 = ap_const_logic_1;
    } else {
        col_inbuf_ce0 = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_col_inbuf_d0() {
    col_inbuf_d0 = (tmp_46_fu_313_p2.read() | tmp_47_fu_319_p2.read());
}

void Loop_Xpose_Row_Outer::thread_col_inbuf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter2_exitcond_flatten_reg_331.read(), ap_const_lv1_0))) {
        col_inbuf_we0 = ap_const_logic_1;
    } else {
        col_inbuf_we0 = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_exitcond_flatten_fu_116_p2() {
    exitcond_flatten_fu_116_p2 = (!indvar_flatten_phi_fu_85_p4.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_phi_fu_85_p4.read() == ap_const_lv7_40);
}

void Loop_Xpose_Row_Outer::thread_i_1_i_mid2_fu_140_p3() {
    i_1_i_mid2_fu_140_p3 = (!tmp_s_fu_134_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_s_fu_134_p2.read()[0].to_bool())? ap_const_lv4_0: i_1_i_phi_fu_108_p4.read());
}

void Loop_Xpose_Row_Outer::thread_i_1_i_phi_fu_108_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00000000.read(), ap_const_boolean_0))) {
        i_1_i_phi_fu_108_p4 = i_reg_368.read();
    } else {
        i_1_i_phi_fu_108_p4 = i_1_i_reg_104.read();
    }
}

void Loop_Xpose_Row_Outer::thread_i_fu_189_p2() {
    i_fu_189_p2 = (!ap_const_lv4_1.is_01() || !i_1_i_mid2_reg_340.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(i_1_i_mid2_reg_340.read()));
}

void Loop_Xpose_Row_Outer::thread_indvar_flatten_next_fu_122_p2() {
    indvar_flatten_next_fu_122_p2 = (!indvar_flatten_phi_fu_85_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_phi_fu_85_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void Loop_Xpose_Row_Outer::thread_indvar_flatten_phi_fu_85_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_331.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
        indvar_flatten_phi_fu_85_p4 = indvar_flatten_next_reg_335.read();
    } else {
        indvar_flatten_phi_fu_85_p4 = indvar_flatten_reg_81.read();
    }
}

void Loop_Xpose_Row_Outer::thread_j_0_i_phi_fu_96_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter1_exitcond_flatten_reg_331.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00000000.read(), ap_const_boolean_0))) {
        j_0_i_phi_fu_96_p4 = tmp_3_mid2_v_reg_346.read();
    } else {
        j_0_i_phi_fu_96_p4 = j_0_i_reg_92.read();
    }
}

void Loop_Xpose_Row_Outer::thread_j_fu_128_p2() {
    j_fu_128_p2 = (!ap_const_lv4_1.is_01() || !j_0_i_phi_fu_96_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(j_0_i_phi_fu_96_p4.read()));
}

void Loop_Xpose_Row_Outer::thread_p_demorgan_fu_263_p2() {
    p_demorgan_fu_263_p2 = (tmp_43_fu_251_p2.read() & tmp_44_fu_257_p2.read());
}

void Loop_Xpose_Row_Outer::thread_row_outbuf_i_address0() {
    row_outbuf_i_address0 =  (sc_lv<6>) (tmp_10_cast_fu_184_p1.read());
}

void Loop_Xpose_Row_Outer::thread_row_outbuf_i_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        row_outbuf_i_ce0 = ap_const_logic_1;
    } else {
        row_outbuf_i_ce0 = ap_const_logic_0;
    }
}

void Loop_Xpose_Row_Outer::thread_tmp_10_cast_fu_184_p1() {
    tmp_10_cast_fu_184_p1 = esl_zext<64,8>(tmp_1_fu_178_p2.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_1_fu_178_p2() {
    tmp_1_fu_178_p2 = (!tmp_9_cast_fu_174_p1.read().is_01() || !tmp_3_mid2_cast_fu_164_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_9_cast_fu_174_p1.read()) + sc_biguint<8>(tmp_3_mid2_cast_fu_164_p1.read()));
}

void Loop_Xpose_Row_Outer::thread_tmp_27_fu_156_p1() {
    tmp_27_fu_156_p1 = i_1_i_mid2_fu_140_p3.read().range(3-1, 0);
}

void Loop_Xpose_Row_Outer::thread_tmp_28_fu_207_p2() {
    tmp_28_fu_207_p2 = (!tmp_4_fu_194_p3.read().is_01() || !tmp_5_fu_201_p2.read().is_01())? sc_lv<1>(): (sc_biguint<7>(tmp_4_fu_194_p3.read()) > sc_biguint<7>(tmp_5_fu_201_p2.read()));
}

void Loop_Xpose_Row_Outer::thread_tmp_29_fu_213_p1() {
    tmp_29_fu_213_p1 = esl_zext<8,7>(tmp_4_fu_194_p3.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_30_fu_217_p1() {
    tmp_30_fu_217_p1 = esl_zext<8,7>(tmp_5_fu_201_p2.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_31_fu_269_p1() {
    tmp_31_fu_269_p1 = esl_zext<128,16>(row_outbuf_i_load_reg_373.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_32_fu_272_p2() {
    tmp_32_fu_272_p2 = (tmp_29_reg_384.read() ^ ap_const_lv8_7F);
}

void Loop_Xpose_Row_Outer::thread_tmp_33_fu_221_p3() {
    tmp_33_fu_221_p3 = (!tmp_28_fu_207_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_28_fu_207_p2.read()[0].to_bool())? tmp_29_fu_213_p1.read(): tmp_30_fu_217_p1.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_34_fu_229_p3() {
    tmp_34_fu_229_p3 = (!tmp_28_fu_207_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_28_fu_207_p2.read()[0].to_bool())? tmp_30_fu_217_p1.read(): tmp_29_fu_213_p1.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_35_fu_277_p3() {
    tmp_35_fu_277_p3 = (!tmp_28_reg_378.read()[0].is_01())? sc_lv<8>(): ((tmp_28_reg_378.read()[0].to_bool())? tmp_32_fu_272_p2.read(): tmp_29_reg_384.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_36_fu_237_p2() {
    tmp_36_fu_237_p2 = (tmp_33_fu_221_p3.read() ^ ap_const_lv8_7F);
}

void Loop_Xpose_Row_Outer::thread_tmp_37_fu_283_p1() {
    tmp_37_fu_283_p1 = esl_zext<128,8>(tmp_35_fu_277_p3.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_38_fu_243_p1() {
    tmp_38_fu_243_p1 = esl_zext<128,8>(tmp_34_fu_229_p3.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_39_fu_247_p1() {
    tmp_39_fu_247_p1 = esl_zext<128,8>(tmp_36_fu_237_p2.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_3_mid2_cast_fu_164_p1() {
    tmp_3_mid2_cast_fu_164_p1 = esl_zext<8,4>(tmp_3_mid2_v_reg_346.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_3_mid2_fu_160_p1() {
    tmp_3_mid2_fu_160_p1 = esl_zext<64,4>(tmp_3_mid2_v_reg_346.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_3_mid2_v_fu_148_p3() {
    tmp_3_mid2_v_fu_148_p3 = (!tmp_s_fu_134_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_s_fu_134_p2.read()[0].to_bool())? j_fu_128_p2.read(): j_0_i_phi_fu_96_p4.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_40_fu_287_p2() {
    tmp_40_fu_287_p2 = (!tmp_37_fu_283_p1.read().is_01())? sc_lv<128>(): tmp_31_fu_269_p1.read() << (unsigned short)tmp_37_fu_283_p1.read().to_uint();
}

void Loop_Xpose_Row_Outer::thread_tmp_41_fu_293_p4() {
    tmp_41_fu_293_p4 = tmp_40_reg_396.read().range(0, 127);
}

void Loop_Xpose_Row_Outer::thread_tmp_42_fu_302_p3() {
    tmp_42_fu_302_p3 = (!tmp_28_reg_378.read()[0].is_01())? sc_lv<128>(): ((tmp_28_reg_378.read()[0].to_bool())? tmp_41_fu_293_p4.read(): tmp_40_reg_396.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_43_fu_251_p2() {
    tmp_43_fu_251_p2 = (!tmp_38_fu_243_p1.read().is_01())? sc_lv<128>(): ap_const_lv128_lc_1 << (unsigned short)tmp_38_fu_243_p1.read().to_uint();
}

void Loop_Xpose_Row_Outer::thread_tmp_44_fu_257_p2() {
    tmp_44_fu_257_p2 = (!tmp_39_fu_247_p1.read().is_01())? sc_lv<128>(): ap_const_lv128_lc_1 >> (unsigned short)tmp_39_fu_247_p1.read().to_uint();
}

void Loop_Xpose_Row_Outer::thread_tmp_45_fu_308_p2() {
    tmp_45_fu_308_p2 = (p_demorgan_reg_390.read() ^ ap_const_lv128_lc_1);
}

void Loop_Xpose_Row_Outer::thread_tmp_46_fu_313_p2() {
    tmp_46_fu_313_p2 = (col_inbuf_q0.read() & tmp_45_fu_308_p2.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_47_fu_319_p2() {
    tmp_47_fu_319_p2 = (tmp_42_fu_302_p3.read() & p_demorgan_reg_390.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_4_fu_194_p3() {
    tmp_4_fu_194_p3 = esl_concat<3,4>(tmp_27_reg_353.read(), ap_const_lv4_0);
}

void Loop_Xpose_Row_Outer::thread_tmp_5_fu_201_p2() {
    tmp_5_fu_201_p2 = (tmp_4_fu_194_p3.read() | ap_const_lv7_F);
}

void Loop_Xpose_Row_Outer::thread_tmp_9_cast_fu_174_p1() {
    tmp_9_cast_fu_174_p1 = esl_zext<8,7>(tmp_fu_167_p3.read());
}

void Loop_Xpose_Row_Outer::thread_tmp_fu_167_p3() {
    tmp_fu_167_p3 = esl_concat<4,3>(i_1_i_mid2_reg_340.read(), ap_const_lv3_0);
}

void Loop_Xpose_Row_Outer::thread_tmp_s_fu_134_p2() {
    tmp_s_fu_134_p2 = (!i_1_i_phi_fu_108_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_1_i_phi_fu_108_p4.read() == ap_const_lv4_8);
}

void Loop_Xpose_Row_Outer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_116_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_116_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

