// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct_1d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_1d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_1d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dct_1d::ap_ST_fsm_state1 = "1";
const sc_lv<3> dct_1d::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> dct_1d::ap_ST_fsm_state8 = "100";
const bool dct_1d::ap_const_boolean_1 = true;
const sc_lv<32> dct_1d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dct_1d::ap_const_lv32_1 = "1";
const bool dct_1d::ap_const_boolean_0 = false;
const sc_lv<1> dct_1d::ap_const_lv1_0 = "0";
const sc_lv<1> dct_1d::ap_const_lv1_1 = "1";
const sc_lv<4> dct_1d::ap_const_lv4_0 = "0000";
const sc_lv<3> dct_1d::ap_const_lv3_0 = "000";
const sc_lv<4> dct_1d::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_1d::ap_const_lv4_1 = "1";
const sc_lv<32> dct_1d::ap_const_lv32_D = "1101";
const sc_lv<32> dct_1d::ap_const_lv32_1C = "11100";
const sc_lv<29> dct_1d::ap_const_lv29_1000 = "1000000000000";
const sc_lv<32> dct_1d::ap_const_lv32_2 = "10";

dct_1d::dct_1d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_0_U = new dct_1d_dct_coeff_bkb("dct_coeff_table_0_U");
    dct_coeff_table_0_U->clk(ap_clk);
    dct_coeff_table_0_U->reset(ap_rst);
    dct_coeff_table_0_U->address0(dct_coeff_table_0_address0);
    dct_coeff_table_0_U->ce0(dct_coeff_table_0_ce0);
    dct_coeff_table_0_U->q0(dct_coeff_table_0_q0);
    dct_coeff_table_1_U = new dct_1d_dct_coeff_cud("dct_coeff_table_1_U");
    dct_coeff_table_1_U->clk(ap_clk);
    dct_coeff_table_1_U->reset(ap_rst);
    dct_coeff_table_1_U->address0(dct_coeff_table_1_address0);
    dct_coeff_table_1_U->ce0(dct_coeff_table_1_ce0);
    dct_coeff_table_1_U->q0(dct_coeff_table_1_q0);
    dct_coeff_table_2_U = new dct_1d_dct_coeff_dEe("dct_coeff_table_2_U");
    dct_coeff_table_2_U->clk(ap_clk);
    dct_coeff_table_2_U->reset(ap_rst);
    dct_coeff_table_2_U->address0(dct_coeff_table_2_address0);
    dct_coeff_table_2_U->ce0(dct_coeff_table_2_ce0);
    dct_coeff_table_2_U->q0(dct_coeff_table_2_q0);
    dct_coeff_table_3_U = new dct_1d_dct_coeff_eOg("dct_coeff_table_3_U");
    dct_coeff_table_3_U->clk(ap_clk);
    dct_coeff_table_3_U->reset(ap_rst);
    dct_coeff_table_3_U->address0(dct_coeff_table_3_address0);
    dct_coeff_table_3_U->ce0(dct_coeff_table_3_ce0);
    dct_coeff_table_3_U->q0(dct_coeff_table_3_q0);
    dct_coeff_table_4_U = new dct_1d_dct_coeff_fYi("dct_coeff_table_4_U");
    dct_coeff_table_4_U->clk(ap_clk);
    dct_coeff_table_4_U->reset(ap_rst);
    dct_coeff_table_4_U->address0(dct_coeff_table_4_address0);
    dct_coeff_table_4_U->ce0(dct_coeff_table_4_ce0);
    dct_coeff_table_4_U->q0(dct_coeff_table_4_q0);
    dct_coeff_table_5_U = new dct_1d_dct_coeff_g8j("dct_coeff_table_5_U");
    dct_coeff_table_5_U->clk(ap_clk);
    dct_coeff_table_5_U->reset(ap_rst);
    dct_coeff_table_5_U->address0(dct_coeff_table_5_address0);
    dct_coeff_table_5_U->ce0(dct_coeff_table_5_ce0);
    dct_coeff_table_5_U->q0(dct_coeff_table_5_q0);
    dct_coeff_table_6_U = new dct_1d_dct_coeff_hbi("dct_coeff_table_6_U");
    dct_coeff_table_6_U->clk(ap_clk);
    dct_coeff_table_6_U->reset(ap_rst);
    dct_coeff_table_6_U->address0(dct_coeff_table_6_address0);
    dct_coeff_table_6_U->ce0(dct_coeff_table_6_ce0);
    dct_coeff_table_6_U->q0(dct_coeff_table_6_q0);
    dct_coeff_table_7_U = new dct_1d_dct_coeff_ibs("dct_coeff_table_7_U");
    dct_coeff_table_7_U->clk(ap_clk);
    dct_coeff_table_7_U->reset(ap_rst);
    dct_coeff_table_7_U->address0(dct_coeff_table_7_address0);
    dct_coeff_table_7_U->ce0(dct_coeff_table_7_ce0);
    dct_coeff_table_7_U->q0(dct_coeff_table_7_q0);
    dct_mul_mul_16s_1jbC_U10 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U10");
    dct_mul_mul_16s_1jbC_U10->din0(src1_load_reg_578);
    dct_mul_mul_16s_1jbC_U10->din1(dct_coeff_table_1_lo_reg_573);
    dct_mul_mul_16s_1jbC_U10->dout(tmp_18_1_fu_428_p2);
    dct_mul_mul_16s_1jbC_U11 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U11");
    dct_mul_mul_16s_1jbC_U11->din0(src3_load_reg_593);
    dct_mul_mul_16s_1jbC_U11->din1(dct_coeff_table_3_lo_reg_588);
    dct_mul_mul_16s_1jbC_U11->dout(tmp_18_3_fu_434_p2);
    dct_mul_mul_16s_1jbC_U12 = new dct_mul_mul_16s_1jbC<1,1,16,15,29>("dct_mul_mul_16s_1jbC_U12");
    dct_mul_mul_16s_1jbC_U12->din0(src5_load_reg_608);
    dct_mul_mul_16s_1jbC_U12->din1(dct_coeff_table_5_lo_reg_603);
    dct_mul_mul_16s_1jbC_U12->dout(tmp_18_5_fu_440_p2);
    dct_mac_muladd_16kbM_U13 = new dct_mac_muladd_16kbM<1,1,16,14,29,29>("dct_mac_muladd_16kbM_U13");
    dct_mac_muladd_16kbM_U13->din0(src_load_reg_628);
    dct_mac_muladd_16kbM_U13->din1(grp_fu_446_p1);
    dct_mac_muladd_16kbM_U13->din2(tmp_18_1_reg_633);
    dct_mac_muladd_16kbM_U13->dout(grp_fu_446_p3);
    dct_mac_muladd_16lbW_U14 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U14");
    dct_mac_muladd_16lbW_U14->din0(src2_load_reg_643);
    dct_mac_muladd_16lbW_U14->din1(dct_coeff_table_2_lo_reg_638);
    dct_mac_muladd_16lbW_U14->din2(tmp_18_3_reg_648);
    dct_mac_muladd_16lbW_U14->dout(grp_fu_454_p3);
    dct_mac_muladd_16lbW_U15 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U15");
    dct_mac_muladd_16lbW_U15->din0(src4_load_reg_658);
    dct_mac_muladd_16lbW_U15->din1(dct_coeff_table_4_lo_reg_653);
    dct_mac_muladd_16lbW_U15->din2(tmp_18_5_reg_663);
    dct_mac_muladd_16lbW_U15->dout(grp_fu_462_p3);
    dct_mac_muladd_16lbW_U16 = new dct_mac_muladd_16lbW<1,1,16,15,29,29>("dct_mac_muladd_16lbW_U16");
    dct_mac_muladd_16lbW_U16->din0(src6_load_reg_673);
    dct_mac_muladd_16lbW_U16->din1(dct_coeff_table_6_lo_reg_668);
    dct_mac_muladd_16lbW_U16->din2(grp_fu_476_p3);
    dct_mac_muladd_16lbW_U16->dout(grp_fu_469_p3);
    dct_mac_muladd_16mb6_U17 = new dct_mac_muladd_16mb6<1,1,16,15,14,29>("dct_mac_muladd_16mb6_U17");
    dct_mac_muladd_16mb6_U17->din0(src7_load_reg_683);
    dct_mac_muladd_16mb6_U17->din1(dct_coeff_table_7_lo_reg_678);
    dct_mac_muladd_16mb6_U17->din2(grp_fu_476_p2);
    dct_mac_muladd_16mb6_U17->dout(grp_fu_476_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( tmp_fu_325_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_dct_coeff_table_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_s_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dct_coeff_table_1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_s_fu_337_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dct_coeff_table_2_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_s_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dct_coeff_table_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_s_fu_337_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dct_coeff_table_4_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_s_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_4_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dct_coeff_table_5_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_s_fu_337_p1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dct_coeff_table_6_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_s_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_6_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dct_coeff_table_7_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_s_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dct_coeff_table_7_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_dst_address0);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( tmp_18_cast_fu_424_p1 );

    SC_METHOD(thread_dst_ce0);
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_dst_d0);
    sensitive << ( tmp_13_reg_703 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_dst_we0);
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_reg_pp0_iter4_tmp_reg_530 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_grp_fu_446_p1);
    sensitive << ( ap_reg_pp0_iter2_tmp_reg_530 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( grp_fu_446_p10 );

    SC_METHOD(thread_grp_fu_446_p10);
    sensitive << ( dct_coeff_table_0_lo_reg_623 );

    SC_METHOD(thread_grp_fu_476_p2);
    sensitive << ( ap_reg_pp0_iter2_tmp_reg_530 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_k_1_fu_331_p2);
    sensitive << ( k_reg_290 );

    SC_METHOD(thread_src1_address0);
    sensitive << ( src1_addr_reg_495 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_src2_address0);
    sensitive << ( src2_addr_reg_500 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_src3_address0);
    sensitive << ( src3_addr_reg_505 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_src4_address0);
    sensitive << ( src4_addr_reg_510 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src4_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_src5_address0);
    sensitive << ( src5_addr_reg_515 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_src6_address0);
    sensitive << ( src6_addr_reg_520 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src6_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_src7_address0);
    sensitive << ( src7_addr_reg_525 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src7_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_src_address0);
    sensitive << ( src_addr_reg_490 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_src_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp1_fu_401_p2);
    sensitive << ( grp_fu_446_p3 );
    sensitive << ( grp_fu_454_p3 );

    SC_METHOD(thread_tmp4_fu_405_p2);
    sensitive << ( tmp5_reg_693 );
    sensitive << ( tmp6_reg_698 );

    SC_METHOD(thread_tmp_11_fu_409_p2);
    sensitive << ( tmp1_reg_688 );
    sensitive << ( tmp4_fu_405_p2 );

    SC_METHOD(thread_tmp_15_fu_301_p3);
    sensitive << ( tmp_61 );

    SC_METHOD(thread_tmp_16_fu_348_p2);
    sensitive << ( tmp_17_cast1_reg_485 );
    sensitive << ( tmp_cast_fu_344_p1 );

    SC_METHOD(thread_tmp_17_cast1_fu_309_p1);
    sensitive << ( tmp_15_fu_301_p3 );

    SC_METHOD(thread_tmp_18_cast_fu_424_p1);
    sensitive << ( ap_reg_pp0_iter4_tmp_16_reg_548 );

    SC_METHOD(thread_tmp_6_cast_fu_313_p1);
    sensitive << ( tmp_6 );

    SC_METHOD(thread_tmp_cast_fu_344_p1);
    sensitive << ( k_reg_290 );

    SC_METHOD(thread_tmp_fu_325_p2);
    sensitive << ( k_reg_290 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_s_fu_337_p1);
    sensitive << ( k_reg_290 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_325_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_1d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_address0, "(port)src_address0");
    sc_trace(mVcdFile, src_ce0, "(port)src_ce0");
    sc_trace(mVcdFile, src_q0, "(port)src_q0");
    sc_trace(mVcdFile, src1_address0, "(port)src1_address0");
    sc_trace(mVcdFile, src1_ce0, "(port)src1_ce0");
    sc_trace(mVcdFile, src1_q0, "(port)src1_q0");
    sc_trace(mVcdFile, src2_address0, "(port)src2_address0");
    sc_trace(mVcdFile, src2_ce0, "(port)src2_ce0");
    sc_trace(mVcdFile, src2_q0, "(port)src2_q0");
    sc_trace(mVcdFile, src3_address0, "(port)src3_address0");
    sc_trace(mVcdFile, src3_ce0, "(port)src3_ce0");
    sc_trace(mVcdFile, src3_q0, "(port)src3_q0");
    sc_trace(mVcdFile, src4_address0, "(port)src4_address0");
    sc_trace(mVcdFile, src4_ce0, "(port)src4_ce0");
    sc_trace(mVcdFile, src4_q0, "(port)src4_q0");
    sc_trace(mVcdFile, src5_address0, "(port)src5_address0");
    sc_trace(mVcdFile, src5_ce0, "(port)src5_ce0");
    sc_trace(mVcdFile, src5_q0, "(port)src5_q0");
    sc_trace(mVcdFile, src6_address0, "(port)src6_address0");
    sc_trace(mVcdFile, src6_ce0, "(port)src6_ce0");
    sc_trace(mVcdFile, src6_q0, "(port)src6_q0");
    sc_trace(mVcdFile, src7_address0, "(port)src7_address0");
    sc_trace(mVcdFile, src7_ce0, "(port)src7_ce0");
    sc_trace(mVcdFile, src7_q0, "(port)src7_q0");
    sc_trace(mVcdFile, tmp_6, "(port)tmp_6");
    sc_trace(mVcdFile, dst_address0, "(port)dst_address0");
    sc_trace(mVcdFile, dst_ce0, "(port)dst_ce0");
    sc_trace(mVcdFile, dst_we0, "(port)dst_we0");
    sc_trace(mVcdFile, dst_d0, "(port)dst_d0");
    sc_trace(mVcdFile, tmp_61, "(port)tmp_61");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dct_coeff_table_0_address0, "dct_coeff_table_0_address0");
    sc_trace(mVcdFile, dct_coeff_table_0_ce0, "dct_coeff_table_0_ce0");
    sc_trace(mVcdFile, dct_coeff_table_0_q0, "dct_coeff_table_0_q0");
    sc_trace(mVcdFile, dct_coeff_table_1_address0, "dct_coeff_table_1_address0");
    sc_trace(mVcdFile, dct_coeff_table_1_ce0, "dct_coeff_table_1_ce0");
    sc_trace(mVcdFile, dct_coeff_table_1_q0, "dct_coeff_table_1_q0");
    sc_trace(mVcdFile, dct_coeff_table_2_address0, "dct_coeff_table_2_address0");
    sc_trace(mVcdFile, dct_coeff_table_2_ce0, "dct_coeff_table_2_ce0");
    sc_trace(mVcdFile, dct_coeff_table_2_q0, "dct_coeff_table_2_q0");
    sc_trace(mVcdFile, dct_coeff_table_3_address0, "dct_coeff_table_3_address0");
    sc_trace(mVcdFile, dct_coeff_table_3_ce0, "dct_coeff_table_3_ce0");
    sc_trace(mVcdFile, dct_coeff_table_3_q0, "dct_coeff_table_3_q0");
    sc_trace(mVcdFile, dct_coeff_table_4_address0, "dct_coeff_table_4_address0");
    sc_trace(mVcdFile, dct_coeff_table_4_ce0, "dct_coeff_table_4_ce0");
    sc_trace(mVcdFile, dct_coeff_table_4_q0, "dct_coeff_table_4_q0");
    sc_trace(mVcdFile, dct_coeff_table_5_address0, "dct_coeff_table_5_address0");
    sc_trace(mVcdFile, dct_coeff_table_5_ce0, "dct_coeff_table_5_ce0");
    sc_trace(mVcdFile, dct_coeff_table_5_q0, "dct_coeff_table_5_q0");
    sc_trace(mVcdFile, dct_coeff_table_6_address0, "dct_coeff_table_6_address0");
    sc_trace(mVcdFile, dct_coeff_table_6_ce0, "dct_coeff_table_6_ce0");
    sc_trace(mVcdFile, dct_coeff_table_6_q0, "dct_coeff_table_6_q0");
    sc_trace(mVcdFile, dct_coeff_table_7_address0, "dct_coeff_table_7_address0");
    sc_trace(mVcdFile, dct_coeff_table_7_ce0, "dct_coeff_table_7_ce0");
    sc_trace(mVcdFile, dct_coeff_table_7_q0, "dct_coeff_table_7_q0");
    sc_trace(mVcdFile, k_reg_290, "k_reg_290");
    sc_trace(mVcdFile, tmp_17_cast1_fu_309_p1, "tmp_17_cast1_fu_309_p1");
    sc_trace(mVcdFile, tmp_17_cast1_reg_485, "tmp_17_cast1_reg_485");
    sc_trace(mVcdFile, src_addr_reg_490, "src_addr_reg_490");
    sc_trace(mVcdFile, src1_addr_reg_495, "src1_addr_reg_495");
    sc_trace(mVcdFile, src2_addr_reg_500, "src2_addr_reg_500");
    sc_trace(mVcdFile, src3_addr_reg_505, "src3_addr_reg_505");
    sc_trace(mVcdFile, src4_addr_reg_510, "src4_addr_reg_510");
    sc_trace(mVcdFile, src5_addr_reg_515, "src5_addr_reg_515");
    sc_trace(mVcdFile, src6_addr_reg_520, "src6_addr_reg_520");
    sc_trace(mVcdFile, src7_addr_reg_525, "src7_addr_reg_525");
    sc_trace(mVcdFile, tmp_fu_325_p2, "tmp_fu_325_p2");
    sc_trace(mVcdFile, tmp_reg_530, "tmp_reg_530");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_530, "ap_reg_pp0_iter1_tmp_reg_530");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_reg_530, "ap_reg_pp0_iter2_tmp_reg_530");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_tmp_reg_530, "ap_reg_pp0_iter3_tmp_reg_530");
    sc_trace(mVcdFile, ap_reg_pp0_iter4_tmp_reg_530, "ap_reg_pp0_iter4_tmp_reg_530");
    sc_trace(mVcdFile, k_1_fu_331_p2, "k_1_fu_331_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_s_fu_337_p1, "tmp_s_fu_337_p1");
    sc_trace(mVcdFile, tmp_s_reg_539, "tmp_s_reg_539");
    sc_trace(mVcdFile, tmp_16_fu_348_p2, "tmp_16_fu_348_p2");
    sc_trace(mVcdFile, tmp_16_reg_548, "tmp_16_reg_548");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_16_reg_548, "ap_reg_pp0_iter1_tmp_16_reg_548");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_16_reg_548, "ap_reg_pp0_iter2_tmp_16_reg_548");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_tmp_16_reg_548, "ap_reg_pp0_iter3_tmp_16_reg_548");
    sc_trace(mVcdFile, ap_reg_pp0_iter4_tmp_16_reg_548, "ap_reg_pp0_iter4_tmp_16_reg_548");
    sc_trace(mVcdFile, dct_coeff_table_1_lo_reg_573, "dct_coeff_table_1_lo_reg_573");
    sc_trace(mVcdFile, src1_load_reg_578, "src1_load_reg_578");
    sc_trace(mVcdFile, dct_coeff_table_3_lo_reg_588, "dct_coeff_table_3_lo_reg_588");
    sc_trace(mVcdFile, src3_load_reg_593, "src3_load_reg_593");
    sc_trace(mVcdFile, dct_coeff_table_5_lo_reg_603, "dct_coeff_table_5_lo_reg_603");
    sc_trace(mVcdFile, src5_load_reg_608, "src5_load_reg_608");
    sc_trace(mVcdFile, dct_coeff_table_0_lo_reg_623, "dct_coeff_table_0_lo_reg_623");
    sc_trace(mVcdFile, src_load_reg_628, "src_load_reg_628");
    sc_trace(mVcdFile, tmp_18_1_fu_428_p2, "tmp_18_1_fu_428_p2");
    sc_trace(mVcdFile, tmp_18_1_reg_633, "tmp_18_1_reg_633");
    sc_trace(mVcdFile, dct_coeff_table_2_lo_reg_638, "dct_coeff_table_2_lo_reg_638");
    sc_trace(mVcdFile, src2_load_reg_643, "src2_load_reg_643");
    sc_trace(mVcdFile, tmp_18_3_fu_434_p2, "tmp_18_3_fu_434_p2");
    sc_trace(mVcdFile, tmp_18_3_reg_648, "tmp_18_3_reg_648");
    sc_trace(mVcdFile, dct_coeff_table_4_lo_reg_653, "dct_coeff_table_4_lo_reg_653");
    sc_trace(mVcdFile, src4_load_reg_658, "src4_load_reg_658");
    sc_trace(mVcdFile, tmp_18_5_fu_440_p2, "tmp_18_5_fu_440_p2");
    sc_trace(mVcdFile, tmp_18_5_reg_663, "tmp_18_5_reg_663");
    sc_trace(mVcdFile, dct_coeff_table_6_lo_reg_668, "dct_coeff_table_6_lo_reg_668");
    sc_trace(mVcdFile, src6_load_reg_673, "src6_load_reg_673");
    sc_trace(mVcdFile, dct_coeff_table_7_lo_reg_678, "dct_coeff_table_7_lo_reg_678");
    sc_trace(mVcdFile, src7_load_reg_683, "src7_load_reg_683");
    sc_trace(mVcdFile, tmp1_fu_401_p2, "tmp1_fu_401_p2");
    sc_trace(mVcdFile, tmp1_reg_688, "tmp1_reg_688");
    sc_trace(mVcdFile, grp_fu_462_p3, "grp_fu_462_p3");
    sc_trace(mVcdFile, tmp5_reg_693, "tmp5_reg_693");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, grp_fu_469_p3, "grp_fu_469_p3");
    sc_trace(mVcdFile, tmp6_reg_698, "tmp6_reg_698");
    sc_trace(mVcdFile, tmp_13_reg_703, "tmp_13_reg_703");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, tmp_6_cast_fu_313_p1, "tmp_6_cast_fu_313_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, tmp_18_cast_fu_424_p1, "tmp_18_cast_fu_424_p1");
    sc_trace(mVcdFile, tmp_15_fu_301_p3, "tmp_15_fu_301_p3");
    sc_trace(mVcdFile, tmp_cast_fu_344_p1, "tmp_cast_fu_344_p1");
    sc_trace(mVcdFile, grp_fu_446_p3, "grp_fu_446_p3");
    sc_trace(mVcdFile, grp_fu_454_p3, "grp_fu_454_p3");
    sc_trace(mVcdFile, tmp4_fu_405_p2, "tmp4_fu_405_p2");
    sc_trace(mVcdFile, tmp_11_fu_409_p2, "tmp_11_fu_409_p2");
    sc_trace(mVcdFile, grp_fu_446_p1, "grp_fu_446_p1");
    sc_trace(mVcdFile, grp_fu_476_p3, "grp_fu_476_p3");
    sc_trace(mVcdFile, grp_fu_476_p2, "grp_fu_476_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_446_p10, "grp_fu_446_p10");
#endif

    }
}

dct_1d::~dct_1d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_0_U;
    delete dct_coeff_table_1_U;
    delete dct_coeff_table_2_U;
    delete dct_coeff_table_3_U;
    delete dct_coeff_table_4_U;
    delete dct_coeff_table_5_U;
    delete dct_coeff_table_6_U;
    delete dct_coeff_table_7_U;
    delete dct_mul_mul_16s_1jbC_U10;
    delete dct_mul_mul_16s_1jbC_U11;
    delete dct_mul_mul_16s_1jbC_U12;
    delete dct_mac_muladd_16kbM_U13;
    delete dct_mac_muladd_16lbW_U14;
    delete dct_mac_muladd_16lbW_U15;
    delete dct_mac_muladd_16lbW_U16;
    delete dct_mac_muladd_16mb6_U17;
}

void dct_1d::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter5 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(tmp_fu_325_p2.read(), ap_const_lv1_0))) {
        k_reg_290 = k_1_fu_331_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_reg_290 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_tmp_16_reg_548 = tmp_16_reg_548.read();
        ap_reg_pp0_iter1_tmp_reg_530 = tmp_reg_530.read();
        tmp_reg_530 = tmp_fu_325_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0)) {
        ap_reg_pp0_iter2_tmp_16_reg_548 = ap_reg_pp0_iter1_tmp_16_reg_548.read();
        ap_reg_pp0_iter2_tmp_reg_530 = ap_reg_pp0_iter1_tmp_reg_530.read();
        ap_reg_pp0_iter3_tmp_16_reg_548 = ap_reg_pp0_iter2_tmp_16_reg_548.read();
        ap_reg_pp0_iter3_tmp_reg_530 = ap_reg_pp0_iter2_tmp_reg_530.read();
        ap_reg_pp0_iter4_tmp_16_reg_548 = ap_reg_pp0_iter3_tmp_16_reg_548.read();
        ap_reg_pp0_iter4_tmp_reg_530 = ap_reg_pp0_iter3_tmp_reg_530.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter1_tmp_reg_530.read(), ap_const_lv1_0))) {
        dct_coeff_table_0_lo_reg_623 = dct_coeff_table_0_q0.read();
        dct_coeff_table_2_lo_reg_638 = dct_coeff_table_2_q0.read();
        dct_coeff_table_4_lo_reg_653 = dct_coeff_table_4_q0.read();
        dct_coeff_table_6_lo_reg_668 = dct_coeff_table_6_q0.read();
        dct_coeff_table_7_lo_reg_678 = dct_coeff_table_7_q0.read();
        src2_load_reg_643 = src2_q0.read();
        src4_load_reg_658 = src4_q0.read();
        src6_load_reg_673 = src6_q0.read();
        src7_load_reg_683 = src7_q0.read();
        src_load_reg_628 = src_q0.read();
        tmp_18_1_reg_633 = tmp_18_1_fu_428_p2.read();
        tmp_18_3_reg_648 = tmp_18_3_fu_434_p2.read();
        tmp_18_5_reg_663 = tmp_18_5_fu_440_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_reg_530.read(), ap_const_lv1_0))) {
        dct_coeff_table_1_lo_reg_573 = dct_coeff_table_1_q0.read();
        dct_coeff_table_3_lo_reg_588 = dct_coeff_table_3_q0.read();
        dct_coeff_table_5_lo_reg_603 = dct_coeff_table_5_q0.read();
        src1_load_reg_578 = src1_q0.read();
        src3_load_reg_593 = src3_q0.read();
        src5_load_reg_608 = src5_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        src1_addr_reg_495 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src2_addr_reg_500 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src3_addr_reg_505 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src4_addr_reg_510 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src5_addr_reg_515 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src6_addr_reg_520 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src7_addr_reg_525 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        src_addr_reg_490 =  (sc_lv<3>) (tmp_6_cast_fu_313_p1.read());
        tmp_17_cast1_reg_485 = tmp_17_cast1_fu_309_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter2_tmp_reg_530.read(), ap_const_lv1_0))) {
        tmp1_reg_688 = tmp1_fu_401_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter2_tmp_reg_530.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        tmp5_reg_693 = grp_fu_462_p3.read();
        tmp6_reg_698 = grp_fu_469_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reg_pp0_iter3_tmp_reg_530.read(), ap_const_lv1_0))) {
        tmp_13_reg_703 = tmp_11_fu_409_p2.read().range(28, 13);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_fu_325_p2.read(), ap_const_lv1_0))) {
        tmp_16_reg_548 = tmp_16_fu_348_p2.read();
        tmp_s_reg_539 = tmp_s_fu_337_p1.read();
    }
}

void dct_1d::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dct_1d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dct_1d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[2];
}

void dct_1d::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct_1d::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(tmp_fu_325_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dct_1d::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_1d::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dct_1d::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_1d::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dct_1d::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_0_address0() {
    dct_coeff_table_0_address0 =  (sc_lv<3>) (tmp_s_reg_539.read());
}

void dct_1d::thread_dct_coeff_table_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dct_coeff_table_0_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_0_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_1_address0() {
    dct_coeff_table_1_address0 =  (sc_lv<3>) (tmp_s_fu_337_p1.read());
}

void dct_1d::thread_dct_coeff_table_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        dct_coeff_table_1_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_1_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_2_address0() {
    dct_coeff_table_2_address0 =  (sc_lv<3>) (tmp_s_reg_539.read());
}

void dct_1d::thread_dct_coeff_table_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dct_coeff_table_2_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_2_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_3_address0() {
    dct_coeff_table_3_address0 =  (sc_lv<3>) (tmp_s_fu_337_p1.read());
}

void dct_1d::thread_dct_coeff_table_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        dct_coeff_table_3_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_3_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_4_address0() {
    dct_coeff_table_4_address0 =  (sc_lv<3>) (tmp_s_reg_539.read());
}

void dct_1d::thread_dct_coeff_table_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dct_coeff_table_4_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_4_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_5_address0() {
    dct_coeff_table_5_address0 =  (sc_lv<3>) (tmp_s_fu_337_p1.read());
}

void dct_1d::thread_dct_coeff_table_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        dct_coeff_table_5_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_5_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_6_address0() {
    dct_coeff_table_6_address0 =  (sc_lv<3>) (tmp_s_reg_539.read());
}

void dct_1d::thread_dct_coeff_table_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dct_coeff_table_6_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_6_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dct_coeff_table_7_address0() {
    dct_coeff_table_7_address0 =  (sc_lv<3>) (tmp_s_reg_539.read());
}

void dct_1d::thread_dct_coeff_table_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        dct_coeff_table_7_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_7_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dst_address0() {
    dst_address0 =  (sc_lv<6>) (tmp_18_cast_fu_424_p1.read());
}

void dct_1d::thread_dst_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        dst_ce0 = ap_const_logic_1;
    } else {
        dst_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_dst_d0() {
    dst_d0 = tmp_13_reg_703.read();
}

void dct_1d::thread_dst_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp0_iter4_tmp_reg_530.read(), ap_const_lv1_0))) {
        dst_we0 = ap_const_logic_1;
    } else {
        dst_we0 = ap_const_logic_0;
    }
}

void dct_1d::thread_grp_fu_446_p1() {
    grp_fu_446_p1 =  (sc_lv<14>) (grp_fu_446_p10.read());
}

void dct_1d::thread_grp_fu_446_p10() {
    grp_fu_446_p10 = esl_zext<29,14>(dct_coeff_table_0_lo_reg_623.read());
}

void dct_1d::thread_grp_fu_476_p2() {
    grp_fu_476_p2 =  (sc_lv<14>) (ap_const_lv29_1000);
}

void dct_1d::thread_k_1_fu_331_p2() {
    k_1_fu_331_p2 = (!k_reg_290.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_reg_290.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_1d::thread_src1_address0() {
    src1_address0 = src1_addr_reg_495.read();
}

void dct_1d::thread_src1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        src1_ce0 = ap_const_logic_1;
    } else {
        src1_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src2_address0() {
    src2_address0 = src2_addr_reg_500.read();
}

void dct_1d::thread_src2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        src2_ce0 = ap_const_logic_1;
    } else {
        src2_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src3_address0() {
    src3_address0 = src3_addr_reg_505.read();
}

void dct_1d::thread_src3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        src3_ce0 = ap_const_logic_1;
    } else {
        src3_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src4_address0() {
    src4_address0 = src4_addr_reg_510.read();
}

void dct_1d::thread_src4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        src4_ce0 = ap_const_logic_1;
    } else {
        src4_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src5_address0() {
    src5_address0 = src5_addr_reg_515.read();
}

void dct_1d::thread_src5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        src5_ce0 = ap_const_logic_1;
    } else {
        src5_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src6_address0() {
    src6_address0 = src6_addr_reg_520.read();
}

void dct_1d::thread_src6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        src6_ce0 = ap_const_logic_1;
    } else {
        src6_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src7_address0() {
    src7_address0 = src7_addr_reg_525.read();
}

void dct_1d::thread_src7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        src7_ce0 = ap_const_logic_1;
    } else {
        src7_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_src_address0() {
    src_address0 = src_addr_reg_490.read();
}

void dct_1d::thread_src_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        src_ce0 = ap_const_logic_1;
    } else {
        src_ce0 = ap_const_logic_0;
    }
}

void dct_1d::thread_tmp1_fu_401_p2() {
    tmp1_fu_401_p2 = (!grp_fu_446_p3.read().is_01() || !grp_fu_454_p3.read().is_01())? sc_lv<29>(): (sc_bigint<29>(grp_fu_446_p3.read()) + sc_bigint<29>(grp_fu_454_p3.read()));
}

void dct_1d::thread_tmp4_fu_405_p2() {
    tmp4_fu_405_p2 = (!tmp5_reg_693.read().is_01() || !tmp6_reg_698.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp5_reg_693.read()) + sc_bigint<29>(tmp6_reg_698.read()));
}

void dct_1d::thread_tmp_11_fu_409_p2() {
    tmp_11_fu_409_p2 = (!tmp1_reg_688.read().is_01() || !tmp4_fu_405_p2.read().is_01())? sc_lv<29>(): (sc_biguint<29>(tmp1_reg_688.read()) + sc_biguint<29>(tmp4_fu_405_p2.read()));
}

void dct_1d::thread_tmp_15_fu_301_p3() {
    tmp_15_fu_301_p3 = esl_concat<4,3>(tmp_61.read(), ap_const_lv3_0);
}

void dct_1d::thread_tmp_16_fu_348_p2() {
    tmp_16_fu_348_p2 = (!tmp_17_cast1_reg_485.read().is_01() || !tmp_cast_fu_344_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_17_cast1_reg_485.read()) + sc_biguint<8>(tmp_cast_fu_344_p1.read()));
}

void dct_1d::thread_tmp_17_cast1_fu_309_p1() {
    tmp_17_cast1_fu_309_p1 = esl_zext<8,7>(tmp_15_fu_301_p3.read());
}

void dct_1d::thread_tmp_18_cast_fu_424_p1() {
    tmp_18_cast_fu_424_p1 = esl_zext<64,8>(ap_reg_pp0_iter4_tmp_16_reg_548.read());
}

void dct_1d::thread_tmp_6_cast_fu_313_p1() {
    tmp_6_cast_fu_313_p1 = esl_zext<64,4>(tmp_6.read());
}

void dct_1d::thread_tmp_cast_fu_344_p1() {
    tmp_cast_fu_344_p1 = esl_zext<8,4>(k_reg_290.read());
}

void dct_1d::thread_tmp_fu_325_p2() {
    tmp_fu_325_p2 = (!k_reg_290.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_290.read() == ap_const_lv4_8);
}

void dct_1d::thread_tmp_s_fu_337_p1() {
    tmp_s_fu_337_p1 = esl_zext<64,4>(k_reg_290.read());
}

void dct_1d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_fu_325_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_fu_325_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

