#pragma line 1 "dct.c" ::: -10
#pragma line 1 "dct.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "dct.c" 2 ::: 184
#pragma line 1 "./dct.h" 1 ::: 186
#pragma line 3 "dct.c" 2 ::: 201
#pragma line 1 "./dct_coeff_table.txt" 1 ::: 209
#pragma line 10 "dct.c" 2 ::: 218
#pragma line 10 "dct.c" ::: 221
